#ifndef __OpenViBEPlugins_Global_Defines_H__
#define __OpenViBEPlugins_Global_Defines_H__

// This file was automatically generated by Plugin Inspector

// -----------------------------------------------------
// Stimulation based epoching
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_StimulationBasedEpoching                                                                       OpenViBE::CIdentifier(0x421e3f46, 0x12003e6c)
#define OVP_GD_ClassId_Algorithm_StimulationBasedEpochingDesc                                                                   OpenViBE::CIdentifier(0x2eaf37fc, 0x63195eb8)
#define OVP_GD_Algorithm_StimulationBasedEpoching_InputParameterId_InputSignal                                                  OpenViBE::CIdentifier(0x0ed5c92b, 0xe16bef25)
#define OVP_GD_Algorithm_StimulationBasedEpoching_InputParameterId_OffsetSampleCount                                            OpenViBE::CIdentifier(0x7646ce65, 0xe128fc4e)
#define OVP_GD_Algorithm_StimulationBasedEpoching_InputParameterId_EndTimeOfTheChunkOneWantsToProcess                           OpenViBE::CIdentifier(0x8b552604, 0x10cd1f94)
#define OVP_GD_Algorithm_StimulationBasedEpoching_OutputParameterId_OutputSignal                                                OpenViBE::CIdentifier(0x00d331a2, 0xc13df043)
#define OVP_GD_Algorithm_StimulationBasedEpoching_InputTriggerId_Reset                                                          OpenViBE::CIdentifier(0x6ba44128, 0x418cf901)
#define OVP_GD_Algorithm_StimulationBasedEpoching_InputTriggerId_PerformEpoching                                                OpenViBE::CIdentifier(0xd05579b5, 0x2649a4b2)
#define OVP_GD_Algorithm_StimulationBasedEpoching_OutputTriggerId_EpochingDone                                                  OpenViBE::CIdentifier(0x755bc3fe, 0x24f7b50f)

// -----------------------------------------------------
// Matrix average
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_MatrixAverage                                                                                  OpenViBE::CIdentifier(0x5e5a6c1c, 0x6f6beb03)
#define OVP_GD_ClassId_Algorithm_MatrixAverageDesc                                                                              OpenViBE::CIdentifier(0x1992881f, 0xc938c0f2)
#define OVP_GD_Algorithm_MatrixAverage_InputParameterId_MatrixCount                                                             OpenViBE::CIdentifier(0x08563191, 0xe78bb265)
#define OVP_GD_Algorithm_MatrixAverage_InputParameterId_Matrix                                                                  OpenViBE::CIdentifier(0x913e9c3b, 0x8a62f5e3)
#define OVP_GD_Algorithm_MatrixAverage_InputParameterId_AveragingMethod                                                         OpenViBE::CIdentifier(0xe63cd759, 0xb6ecf6b7)
#define OVP_GD_Algorithm_MatrixAverage_OutputParameterId_AveragedMatrix                                                         OpenViBE::CIdentifier(0x03ce5ae5, 0xbd9031e0)
#define OVP_GD_Algorithm_MatrixAverage_InputTriggerId_FeedMatrix                                                                OpenViBE::CIdentifier(0x50b6ee87, 0xdc42e660)
#define OVP_GD_Algorithm_MatrixAverage_InputTriggerId_Reset                                                                     OpenViBE::CIdentifier(0x670ec053, 0xadfe3f5c)
#define OVP_GD_Algorithm_MatrixAverage_InputTriggerId_ForceAverage                                                              OpenViBE::CIdentifier(0xbf597839, 0xcd6039f0)
#define OVP_GD_Algorithm_MatrixAverage_OutputTriggerId_AveragePerformed                                                         OpenViBE::CIdentifier(0x2bff029b, 0xd932a613)

// -----------------------------------------------------
// OneVsOne pairing classifier
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_OneVsOnePairingClassifier                                                                      OpenViBE::CIdentifier(0x638c2f90, 0xeae10226)
#define OVP_GD_ClassId_Algorithm_OneVsOnePairingClassifierDesc                                                                  OpenViBE::CIdentifier(0xe78e7cdb, 0x369aa9ef)
#define OVP_GD_Algorithm_OneVsOnePairingClassifier_InputParameterId_PairwiseDecisionStrategy                                    OpenViBE::CIdentifier(0x0c347bba, 0x180577f9)
#define OVP_GD_Algorithm_OneVsOnePairingClassifier_InputParameterId_NumberOfClasses                                             OpenViBE::CIdentifier(0x1b95825a, 0x24f2e949)
#define OVP_GD_Algorithm_OneVsOnePairingClassifier_InputParameterId_FeatureVectorSet                                            OpenViBE::CIdentifier(0x27c05927, 0x5de9103a)
#define OVP_GD_Algorithm_OneVsOnePairingClassifier_InputParameterId_ExtraParameter                                              OpenViBE::CIdentifier(0x42ad6be3, 0xf483de3f)
#define OVP_GD_Algorithm_OneVsOnePairingClassifier_InputParameterId_FeatureVector                                               OpenViBE::CIdentifier(0x6d69bf98, 0x1eb9ee66)
#define OVP_GD_Algorithm_OneVsOnePairingClassifier_InputParameterId_Configuration                                               OpenViBE::CIdentifier(0xa705428e, 0x5bb1cadd)
#define OVP_GD_Algorithm_OneVsOnePairingClassifier_InputParameterId_AlgorithmIdentifier                                         OpenViBE::CIdentifier(0xd9e60df9, 0x20ec8fc9)
#define OVP_GD_Algorithm_OneVsOnePairingClassifier_OutputParameterId_Configuration                                              OpenViBE::CIdentifier(0x30590936, 0x61ce5971)
#define OVP_GD_Algorithm_OneVsOnePairingClassifier_OutputParameterId_Class                                                      OpenViBE::CIdentifier(0x8a39a7ea, 0xf2ee45c4)
#define OVP_GD_Algorithm_OneVsOnePairingClassifier_OutputParameterId_HyperplaneDistance                                         OpenViBE::CIdentifier(0xda77d7e4, 0x766b48ea)
#define OVP_GD_Algorithm_OneVsOnePairingClassifier_OutputParameterId_ProbabilityValues                                          OpenViBE::CIdentifier(0xda77d7e4, 0x766b48eb)
#define OVP_GD_Algorithm_OneVsOnePairingClassifier_InputTriggerId_Train                                                         OpenViBE::CIdentifier(0x34684752, 0x78a46de2)
#define OVP_GD_Algorithm_OneVsOnePairingClassifier_InputTriggerId_DesignArchitecture                                            OpenViBE::CIdentifier(0x784a9cdf, 0xa41c27f8)
#define OVP_GD_Algorithm_OneVsOnePairingClassifier_InputTriggerId_SaveConfiguration                                             OpenViBE::CIdentifier(0x79750528, 0x6cc85fc1)
#define OVP_GD_Algorithm_OneVsOnePairingClassifier_InputTriggerId_Classify                                                      OpenViBE::CIdentifier(0x843a87d8, 0x566e85a1)
#define OVP_GD_Algorithm_OneVsOnePairingClassifier_InputTriggerId_LoadConfiguration                                             OpenViBE::CIdentifier(0xf346bbe0, 0xadafc735)
#define OVP_GD_Algorithm_OneVsOnePairingClassifier_OutputTriggerId_Success                                                      OpenViBE::CIdentifier(0x24fab755, 0x78868782)
#define OVP_GD_Algorithm_OneVsOnePairingClassifier_OutputTriggerId_Failed                                                       OpenViBE::CIdentifier(0x6e72b255, 0x317faa04)

// -----------------------------------------------------
// LDA Classifier
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_LDAClassifier                                                                                  OpenViBE::CIdentifier(0x2ba17a3c, 0x1bd46d84)
#define OVP_GD_ClassId_Algorithm_LDAClassifierDesc                                                                              OpenViBE::CIdentifier(0x78fe2929, 0x644945b4)
#define OVP_GD_Algorithm_LDAClassifier_InputParameterId_UseShrinkage                                                            OpenViBE::CIdentifier(0x01357534, 0x028312a0)
#define OVP_GD_Algorithm_LDAClassifier_InputParameterId_ShrinkageCoefficient1Auto                                               OpenViBE::CIdentifier(0x01357534, 0x028312a1)
#define OVP_GD_Algorithm_LDAClassifier_InputParameterId_ShrinkageForceDiagonalCovDDA                                            OpenViBE::CIdentifier(0x067e45c5, 0x15285cc7)
#define OVP_GD_Algorithm_LDAClassifier_InputParameterId_NumberOfClasses                                                         OpenViBE::CIdentifier(0x1b95825a, 0x24f2e949) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputParameterId_NumberOfClasses
#define OVP_GD_Algorithm_LDAClassifier_InputParameterId_FeatureVectorSet                                                        OpenViBE::CIdentifier(0x27c05927, 0x5de9103a) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputParameterId_FeatureVectorSet
#define OVP_GD_Algorithm_LDAClassifier_InputParameterId_ExtraParameter                                                          OpenViBE::CIdentifier(0x42ad6be3, 0xf483de3f) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputParameterId_ExtraParameter
#define OVP_GD_Algorithm_LDAClassifier_InputParameterId_FeatureVector                                                           OpenViBE::CIdentifier(0x6d69bf98, 0x1eb9ee66) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputParameterId_FeatureVector
#define OVP_GD_Algorithm_LDAClassifier_InputParameterId_Configuration                                                           OpenViBE::CIdentifier(0xa705428e, 0x5bb1cadd) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputParameterId_Configuration
#define OVP_GD_Algorithm_LDAClassifier_OutputParameterId_Configuration                                                          OpenViBE::CIdentifier(0x30590936, 0x61ce5971) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_OutputParameterId_Configuration
#define OVP_GD_Algorithm_LDAClassifier_OutputParameterId_Class                                                                  OpenViBE::CIdentifier(0x8a39a7ea, 0xf2ee45c4) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_OutputParameterId_Class
#define OVP_GD_Algorithm_LDAClassifier_OutputParameterId_HyperplaneDistance                                                     OpenViBE::CIdentifier(0xda77d7e4, 0x766b48ea) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_OutputParameterId_HyperplaneDistance
#define OVP_GD_Algorithm_LDAClassifier_OutputParameterId_ProbabilityValues                                                      OpenViBE::CIdentifier(0xda77d7e4, 0x766b48eb) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_OutputParameterId_ProbabilityValues
#define OVP_GD_Algorithm_LDAClassifier_InputTriggerId_Train                                                                     OpenViBE::CIdentifier(0x34684752, 0x78a46de2) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputTriggerId_Train
#define OVP_GD_Algorithm_LDAClassifier_InputTriggerId_SaveConfiguration                                                         OpenViBE::CIdentifier(0x79750528, 0x6cc85fc1) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputTriggerId_SaveConfiguration
#define OVP_GD_Algorithm_LDAClassifier_InputTriggerId_Classify                                                                  OpenViBE::CIdentifier(0x843a87d8, 0x566e85a1) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputTriggerId_Classify
#define OVP_GD_Algorithm_LDAClassifier_InputTriggerId_LoadConfiguration                                                         OpenViBE::CIdentifier(0xf346bbe0, 0xadafc735) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputTriggerId_LoadConfiguration
#define OVP_GD_Algorithm_LDAClassifier_OutputTriggerId_Success                                                                  OpenViBE::CIdentifier(0x24fab755, 0x78868782) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_OutputTriggerId_Success
#define OVP_GD_Algorithm_LDAClassifier_OutputTriggerId_Failed                                                                   OpenViBE::CIdentifier(0x6e72b255, 0x317faa04) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_OutputTriggerId_Failed

// -----------------------------------------------------
// XML Scenario exporter
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_XMLScenarioExporter                                                                            OpenViBE::CIdentifier(0x53693531, 0xb136cf3f)
#define OVP_GD_ClassId_Algorithm_XMLScenarioExporterDesc                                                                        OpenViBE::CIdentifier(0x9709c9fa, 0xf126f74e)
#define OVP_GD_Algorithm_XMLScenarioExporter_InputParameterId_Scenario                                                          OpenViBE::CIdentifier(0x5b9c0d54, 0x04ba2957)
#define OVP_GD_Algorithm_XMLScenarioExporter_OutputParameterId_MemoryBuffer                                                     OpenViBE::CIdentifier(0x64030633, 0x419e3a33)

// -----------------------------------------------------
// OpenViBE Matrix file writer
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_OpenViBEMatrixFileWriter                                                                       OpenViBE::CIdentifier(0x739158fc, 0x1e8240cc)
#define OVP_GD_ClassId_Algorithm_OpenViBEMatrixFileWriterDesc                                                                   OpenViBE::CIdentifier(0x44cf6dd0, 0x329d47f9)
#define OVP_GD_Algorithm_OpenViBEMatrixFileWriter_InputParameterId_Filename                                                     OpenViBE::CIdentifier(0x330d2d0b, 0x175271e6)
#define OVP_GD_Algorithm_OpenViBEMatrixFileWriter_InputParameterId_Matrix                                                       OpenViBE::CIdentifier(0x6f6402ee, 0x493044f3)

// -----------------------------------------------------
// XML Scenario importer
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_XMLScenarioImporter                                                                            OpenViBE::CIdentifier(0xe80c3ea2, 0x149c4a05)
#define OVP_GD_ClassId_Algorithm_XMLScenarioImporterDesc                                                                        OpenViBE::CIdentifier(0xff25d456, 0x721fcc57)
#define OVP_GD_Algorithm_XMLScenarioImporter_InputParameterId_MemoryBuffer                                                      OpenViBE::CIdentifier(0x600463a3, 0x474b7f66)
#define OVP_GD_Algorithm_XMLScenarioImporter_OutputParameterId_Scenario                                                         OpenViBE::CIdentifier(0x29574c87, 0x7ba77780)

// -----------------------------------------------------
// OneVsAll pairing classifier
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_OneVsAllPairingClassifier                                                                      OpenViBE::CIdentifier(0xd7183fc6, 0xbd74f297)
#define OVP_GD_ClassId_Algorithm_OneVsAllPairingClassifierDesc                                                                  OpenViBE::CIdentifier(0xd42d5449, 0x7a28ddb0)
#define OVP_GD_Algorithm_OneVsAllPairingClassifier_InputParameterId_NumberOfClasses                                             OpenViBE::CIdentifier(0x1b95825a, 0x24f2e949) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputParameterId_NumberOfClasses
#define OVP_GD_Algorithm_OneVsAllPairingClassifier_InputParameterId_FeatureVectorSet                                            OpenViBE::CIdentifier(0x27c05927, 0x5de9103a) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputParameterId_FeatureVectorSet
#define OVP_GD_Algorithm_OneVsAllPairingClassifier_InputParameterId_ExtraParameter                                              OpenViBE::CIdentifier(0x42ad6be3, 0xf483de3f) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputParameterId_ExtraParameter
#define OVP_GD_Algorithm_OneVsAllPairingClassifier_InputParameterId_FeatureVector                                               OpenViBE::CIdentifier(0x6d69bf98, 0x1eb9ee66) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputParameterId_FeatureVector
#define OVP_GD_Algorithm_OneVsAllPairingClassifier_InputParameterId_Configuration                                               OpenViBE::CIdentifier(0xa705428e, 0x5bb1cadd) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputParameterId_Configuration
#define OVP_GD_Algorithm_OneVsAllPairingClassifier_InputParameterId_AlgorithmIdentifier                                         OpenViBE::CIdentifier(0xd9e60df9, 0x20ec8fc9) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputParameterId_AlgorithmIdentifier
#define OVP_GD_Algorithm_OneVsAllPairingClassifier_OutputParameterId_Configuration                                              OpenViBE::CIdentifier(0x30590936, 0x61ce5971) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_OutputParameterId_Configuration
#define OVP_GD_Algorithm_OneVsAllPairingClassifier_OutputParameterId_Class                                                      OpenViBE::CIdentifier(0x8a39a7ea, 0xf2ee45c4) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_OutputParameterId_Class
#define OVP_GD_Algorithm_OneVsAllPairingClassifier_OutputParameterId_HyperplaneDistance                                         OpenViBE::CIdentifier(0xda77d7e4, 0x766b48ea) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_OutputParameterId_HyperplaneDistance
#define OVP_GD_Algorithm_OneVsAllPairingClassifier_OutputParameterId_ProbabilityValues                                          OpenViBE::CIdentifier(0xda77d7e4, 0x766b48eb) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_OutputParameterId_ProbabilityValues
#define OVP_GD_Algorithm_OneVsAllPairingClassifier_InputTriggerId_Train                                                         OpenViBE::CIdentifier(0x34684752, 0x78a46de2) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputTriggerId_Train
#define OVP_GD_Algorithm_OneVsAllPairingClassifier_InputTriggerId_DesignArchitecture                                            OpenViBE::CIdentifier(0x784a9cdf, 0xa41c27f8) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputTriggerId_DesignArchitecture
#define OVP_GD_Algorithm_OneVsAllPairingClassifier_InputTriggerId_SaveConfiguration                                             OpenViBE::CIdentifier(0x79750528, 0x6cc85fc1) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputTriggerId_SaveConfiguration
#define OVP_GD_Algorithm_OneVsAllPairingClassifier_InputTriggerId_Classify                                                      OpenViBE::CIdentifier(0x843a87d8, 0x566e85a1) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputTriggerId_Classify
#define OVP_GD_Algorithm_OneVsAllPairingClassifier_InputTriggerId_LoadConfiguration                                             OpenViBE::CIdentifier(0xf346bbe0, 0xadafc735) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_InputTriggerId_LoadConfiguration
#define OVP_GD_Algorithm_OneVsAllPairingClassifier_OutputTriggerId_Success                                                      OpenViBE::CIdentifier(0x24fab755, 0x78868782) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_OutputTriggerId_Success
#define OVP_GD_Algorithm_OneVsAllPairingClassifier_OutputTriggerId_Failed                                                       OpenViBE::CIdentifier(0x6e72b255, 0x317faa04) // Duplicate of OVP_GD_Algorithm_OneVsOnePairingClassifier_OutputTriggerId_Failed

// -----------------------------------------------------
// OpenViBE Matrix file reader
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_OpenViBEMatrixFileReader                                                                       OpenViBE::CIdentifier(0x10661a33, 0x0b0f44a7)
#define OVP_GD_ClassId_Algorithm_OpenViBEMatrixFileReaderDesc                                                                   OpenViBE::CIdentifier(0x0e873b5e, 0x0a287fcb)
#define OVP_GD_Algorithm_OpenViBEMatrixFileReader_InputParameterId_Filename                                                     OpenViBE::CIdentifier(0x28f87b29, 0x0b09737e)
#define OVP_GD_Algorithm_OpenViBEMatrixFileReader_OutputParameterId_Matrix                                                      OpenViBE::CIdentifier(0x2f9521e0, 0x027d789f)

// -----------------------------------------------------
// Conditioned Covariance
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_ConditionedCovariance                                                                          OpenViBE::CIdentifier(0x0f3b77a6, 0x0301518a)
#define OVP_GD_ClassId_Algorithm_ConditionedCovarianceDesc                                                                      OpenViBE::CIdentifier(0x18d15c41, 0x70545a66)
#define OVP_GD_Algorithm_ConditionedCovariance_InputParameterId_FeatureVectors                                                  OpenViBE::CIdentifier(0x2cf30e42, 0x051f3996)
#define OVP_GD_Algorithm_ConditionedCovariance_InputParameterId_Shrinkage1Auto                                                  OpenViBE::CIdentifier(0x54b90ea7, 0x600a4acc)
#define OVP_GD_Algorithm_ConditionedCovariance_OutputParameterId_MeanVector                                                     OpenViBE::CIdentifier(0x0c671fb7, 0x550b01b3)
#define OVP_GD_Algorithm_ConditionedCovariance_OutputParameterId_CovarianceMatrix                                               OpenViBE::CIdentifier(0x19f07fb4, 0x084e273b)

// -----------------------------------------------------
// Pairwise decision strategy based on PKPD
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_PairwiseDecisionStrategyBasedOnPKPD                                                            OpenViBE::CIdentifier(0x26ef6dda, 0xf137053c)
#define OVP_GD_ClassId_Algorithm_PairwiseDecisionStrategyBasedOnPKPDDesc                                                        OpenViBE::CIdentifier(0x191eb02a, 0x6866214a)
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputParameterId_ConfigurationNode                                 OpenViBE::CIdentifier(0x10ebac09, 0x80926a63)
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputParameterId_ClassificationAlgorithm                           OpenViBE::CIdentifier(0xbe71be18, 0x82a0e017)
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputParameterId_SetRepartition                                    OpenViBE::CIdentifier(0xbe71be18, 0x82a0e018)
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputParameterId_ClassificationOutputs                             OpenViBE::CIdentifier(0xbe71be18, 0x82a0e019)
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputParameterId_ClassCount                                        OpenViBE::CIdentifier(0xbe71be18, 0x82a0e01a)
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputParameterId_ProbabilityMatrix                                 OpenViBE::CIdentifier(0xf48d35ad, 0xb8eff834)
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_OutputParameterId_ConfigurationNode                                OpenViBE::CIdentifier(0x69f05a61, 0x25c94515)
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_OutputParameterId_ProbabilityVector                                OpenViBE::CIdentifier(0x883599fe, 0x2fdb32ff)
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputTriggerId_Parametrize                                         OpenViBE::CIdentifier(0x32219d21, 0xd3be6106)
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputTriggerId_Compute                                             OpenViBE::CIdentifier(0x3637344b, 0x05d03d7e)
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputTriggerId_LoadConfiguration                                   OpenViBE::CIdentifier(0x97af6c6c, 0x670a12e6)
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputTriggerId_SaveConfiguration                                   OpenViBE::CIdentifier(0xf19574ad, 0x024045a7)

// -----------------------------------------------------
// Pairwise decision strategy based on Voting
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_PairwiseDecisionStrategyBasedOnVoting                                                          OpenViBE::CIdentifier(0xa111b830, 0x4679bafd)
#define OVP_GD_ClassId_Algorithm_PairwiseDecisionStrategyBasedOnVotingDesc                                                      OpenViBE::CIdentifier(0xac5a39e8, 0x3a57822a)
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnVoting_InputParameterId_ConfigurationNode                               OpenViBE::CIdentifier(0x10ebac09, 0x80926a63) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputParameterId_ConfigurationNode
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnVoting_InputParameterId_ClassificationAlgorithm                         OpenViBE::CIdentifier(0xbe71be18, 0x82a0e017) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputParameterId_ClassificationAlgorithm
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnVoting_InputParameterId_SetRepartition                                  OpenViBE::CIdentifier(0xbe71be18, 0x82a0e018) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputParameterId_SetRepartition
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnVoting_InputParameterId_ClassificationOutputs                           OpenViBE::CIdentifier(0xbe71be18, 0x82a0e019) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputParameterId_ClassificationOutputs
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnVoting_InputParameterId_ClassCount                                      OpenViBE::CIdentifier(0xbe71be18, 0x82a0e01a) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputParameterId_ClassCount
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnVoting_InputParameterId_ProbabilityMatrix                               OpenViBE::CIdentifier(0xf48d35ad, 0xb8eff834) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputParameterId_ProbabilityMatrix
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnVoting_OutputParameterId_ConfigurationNode                              OpenViBE::CIdentifier(0x69f05a61, 0x25c94515) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_OutputParameterId_ConfigurationNode
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnVoting_OutputParameterId_ProbabilityVector                              OpenViBE::CIdentifier(0x883599fe, 0x2fdb32ff) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_OutputParameterId_ProbabilityVector
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnVoting_InputTriggerId_Parametrize                                       OpenViBE::CIdentifier(0x32219d21, 0xd3be6106) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputTriggerId_Parametrize
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnVoting_InputTriggerId_Compute                                           OpenViBE::CIdentifier(0x3637344b, 0x05d03d7e) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputTriggerId_Compute
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnVoting_InputTriggerId_LoadConfiguration                                 OpenViBE::CIdentifier(0x97af6c6c, 0x670a12e6) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputTriggerId_LoadConfiguration
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnVoting_InputTriggerId_SaveConfiguration                                 OpenViBE::CIdentifier(0xf19574ad, 0x024045a7) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputTriggerId_SaveConfiguration

// -----------------------------------------------------
// Pairwise decision strategy based on HT
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_PairwiseDecisionStrategyBasedOnHT                                                              OpenViBE::CIdentifier(0xd24f7f19, 0xa744fad2)
#define OVP_GD_ClassId_Algorithm_PairwiseDecisionStrategyBasedOnHTDesc                                                          OpenViBE::CIdentifier(0xe837f5c0, 0xf65c1341)
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnHT_InputParameterId_ConfigurationNode                                   OpenViBE::CIdentifier(0x10ebac09, 0x80926a63) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputParameterId_ConfigurationNode
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnHT_InputParameterId_ClassificationAlgorithm                             OpenViBE::CIdentifier(0xbe71be18, 0x82a0e017) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputParameterId_ClassificationAlgorithm
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnHT_InputParameterId_SetRepartition                                      OpenViBE::CIdentifier(0xbe71be18, 0x82a0e018) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputParameterId_SetRepartition
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnHT_InputParameterId_ClassificationOutputs                               OpenViBE::CIdentifier(0xbe71be18, 0x82a0e019) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputParameterId_ClassificationOutputs
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnHT_InputParameterId_ClassCount                                          OpenViBE::CIdentifier(0xbe71be18, 0x82a0e01a) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputParameterId_ClassCount
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnHT_InputParameterId_ProbabilityMatrix                                   OpenViBE::CIdentifier(0xf48d35ad, 0xb8eff834) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputParameterId_ProbabilityMatrix
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnHT_OutputParameterId_ConfigurationNode                                  OpenViBE::CIdentifier(0x69f05a61, 0x25c94515) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_OutputParameterId_ConfigurationNode
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnHT_OutputParameterId_ProbabilityVector                                  OpenViBE::CIdentifier(0x883599fe, 0x2fdb32ff) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_OutputParameterId_ProbabilityVector
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnHT_InputTriggerId_Parametrize                                           OpenViBE::CIdentifier(0x32219d21, 0xd3be6106) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputTriggerId_Parametrize
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnHT_InputTriggerId_Compute                                               OpenViBE::CIdentifier(0x3637344b, 0x05d03d7e) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputTriggerId_Compute
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnHT_InputTriggerId_LoadConfiguration                                     OpenViBE::CIdentifier(0x97af6c6c, 0x670a12e6) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputTriggerId_LoadConfiguration
#define OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnHT_InputTriggerId_SaveConfiguration                                     OpenViBE::CIdentifier(0xf19574ad, 0x024045a7) // Duplicate of OVP_GD_Algorithm_PairwiseDecisionStrategyBasedOnPKPD_InputTriggerId_SaveConfiguration

// -----------------------------------------------------
// Online Covariance
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_OnlineCovariance                                                                               OpenViBE::CIdentifier(0x5add4f8e, 0x005d29c1)
#define OVP_GD_ClassId_Algorithm_OnlineCovarianceDesc                                                                           OpenViBE::CIdentifier(0x00cd2dea, 0x4c000ceb)
#define OVP_GD_Algorithm_OnlineCovariance_InputParameterId_Shrinkage                                                            OpenViBE::CIdentifier(0x16577c7b, 0x4e056bf7)
#define OVP_GD_Algorithm_OnlineCovariance_InputParameterId_CovUpdateMethod                                                      OpenViBE::CIdentifier(0x1c4f444f, 0x3ca213e2)
#define OVP_GD_Algorithm_OnlineCovariance_InputParameterId_TraceNormalization                                                   OpenViBE::CIdentifier(0x269d5e63, 0x3b6d486e)
#define OVP_GD_Algorithm_OnlineCovariance_InputParameterId_InputVectors                                                         OpenViBE::CIdentifier(0x47e55f81, 0x27a519c4)
#define OVP_GD_Algorithm_OnlineCovariance_OutputParameterId_CovarianceMatrix                                                    OpenViBE::CIdentifier(0x203a5472, 0x67c5324c)
#define OVP_GD_Algorithm_OnlineCovariance_OutputParameterId_MeanVector                                                          OpenViBE::CIdentifier(0x3f1f50a3, 0x05504d0e)
#define OVP_GD_Algorithm_OnlineCovariance_InputTriggerId_GetTheCurrentCovarianceMatrixMean                                      OpenViBE::CIdentifier(0x0915148c, 0x5f792b2a)
#define OVP_GD_Algorithm_OnlineCovariance_InputTriggerId_GetTheCurrentRegularizedCovarianceMatrixMean                           OpenViBE::CIdentifier(0x2bbc4a91, 0x27050cfd)
#define OVP_GD_Algorithm_OnlineCovariance_InputTriggerId_ResetTheAlgorithm                                                      OpenViBE::CIdentifier(0x4c1c510c, 0x3cf56e7c)
#define OVP_GD_Algorithm_OnlineCovariance_InputTriggerId_AppendAChunkOfData                                                     OpenViBE::CIdentifier(0x72bf2277, 0x2974747b)

// -----------------------------------------------------
// Streamed matrix stream encoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_StreamedMatrixStreamEncoder                                                                    OpenViBE::CIdentifier(0x5cb32c71, 0x576f00a6)
#define OVP_GD_ClassId_Algorithm_StreamedMatrixStreamEncoderDesc                                                                OpenViBE::CIdentifier(0xeeefe060, 0x646ee8ab)
#define OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputParameterId_Matrix                                                    OpenViBE::CIdentifier(0xa3e9e5b0, 0xae756303)
#define OVP_GD_Algorithm_StreamedMatrixStreamEncoder_OutputParameterId_EncodedMemoryBuffer                                      OpenViBE::CIdentifier(0xa3d8b171, 0xf8734734)
#define OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeBuffer                                                OpenViBE::CIdentifier(0x1b7076fd, 0x449bc70a)
#define OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeEnd                                                   OpenViBE::CIdentifier(0x3fc23508, 0x806753d8)
#define OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeHeader                                                OpenViBE::CIdentifier(0x878eaf60, 0xf9d5303f)

// -----------------------------------------------------
// Master acquisition stream encoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_MasterAcquisitionStreamEncoder                                                                 OpenViBE::CIdentifier(0x2d15e00b, 0x51414eb6)
#define OVP_GD_ClassId_Algorithm_MasterAcquisitionStreamEncoderDesc                                                             OpenViBE::CIdentifier(0xe6ec841d, 0x9e75a8fb)
#define OVP_GD_Algorithm_MasterAcquisitionStreamEncoder_InputParameterId_EncodeChannelUnitData                                  OpenViBE::CIdentifier(0x19dc533c, 0x56301d0b)
#define OVP_GD_Algorithm_MasterAcquisitionStreamEncoder_InputParameterId_ChannelLocalisation                                    OpenViBE::CIdentifier(0x227e13f0, 0x206b44f9)
#define OVP_GD_Algorithm_MasterAcquisitionStreamEncoder_InputParameterId_EncodeChannelLocalisationData                          OpenViBE::CIdentifier(0x26ee1f81, 0x3db00d5d)
#define OVP_GD_Algorithm_MasterAcquisitionStreamEncoder_InputParameterId_StimulationSet                                         OpenViBE::CIdentifier(0x5b728d37, 0xfd088887)
#define OVP_GD_Algorithm_MasterAcquisitionStreamEncoder_InputParameterId_ChannelUnits                                           OpenViBE::CIdentifier(0x740060c2, 0x7d2b4f57)
#define OVP_GD_Algorithm_MasterAcquisitionStreamEncoder_InputParameterId_SubjectAge                                             OpenViBE::CIdentifier(0x9ef355e4, 0xc8531112)
#define OVP_GD_Algorithm_MasterAcquisitionStreamEncoder_InputParameterId_SubjectGender                                          OpenViBE::CIdentifier(0xa9056ae3, 0x57fe6af0)
#define OVP_GD_Algorithm_MasterAcquisitionStreamEncoder_InputParameterId_SignalSamplingRate                                     OpenViBE::CIdentifier(0xb84ad0ca, 0x4f316dd3)
#define OVP_GD_Algorithm_MasterAcquisitionStreamEncoder_InputParameterId_SubjectIdentifier                                      OpenViBE::CIdentifier(0xd5bb5231, 0x59389b72)
#define OVP_GD_Algorithm_MasterAcquisitionStreamEncoder_InputParameterId_BufferDuration                                         OpenViBE::CIdentifier(0xe1fc7385, 0x586a4f3f)
#define OVP_GD_Algorithm_MasterAcquisitionStreamEncoder_InputParameterId_SignalMatrix                                           OpenViBE::CIdentifier(0xe9ac8077, 0xe369a51d)
#define OVP_GD_Algorithm_MasterAcquisitionStreamEncoder_OutputParameterId_EncodedMemoryBuffer                                   OpenViBE::CIdentifier(0xa3d8b171, 0xf8734734) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_OutputParameterId_EncodedMemoryBuffer
#define OVP_GD_Algorithm_MasterAcquisitionStreamEncoder_InputTriggerId_EncodeBuffer                                             OpenViBE::CIdentifier(0x1b7076fd, 0x449bc70a) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeBuffer
#define OVP_GD_Algorithm_MasterAcquisitionStreamEncoder_InputTriggerId_EncodeEnd                                                OpenViBE::CIdentifier(0x3fc23508, 0x806753d8) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeEnd
#define OVP_GD_Algorithm_MasterAcquisitionStreamEncoder_InputTriggerId_EncodeHeader                                             OpenViBE::CIdentifier(0x878eaf60, 0xf9d5303f) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeHeader

// -----------------------------------------------------
// Experiment information stream decoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_ExperimentInformationStreamDecoder                                                             OpenViBE::CIdentifier(0x6fa7d52b, 0x80e2abd6)
#define OVP_GD_ClassId_Algorithm_ExperimentInformationStreamDecoderDesc                                                         OpenViBE::CIdentifier(0x0f37ca61, 0x8a77f44e)
#define OVP_GD_Algorithm_ExperimentInformationStreamDecoder_InputParameterId_MemoryBufferToDecode                               OpenViBE::CIdentifier(0x2f98ea3c, 0xfb0be096)
#define OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_SubjectName                                       OpenViBE::CIdentifier(0x3d3826ea, 0xe8883815)
#define OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_ExperimentIdentifier                              OpenViBE::CIdentifier(0x40259641, 0x478c73de)
#define OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_LaboratoryName                                    OpenViBE::CIdentifier(0x5ca80fa5, 0x774f01cb)
#define OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_SubjectGender                                     OpenViBE::CIdentifier(0x7d5059e8, 0xe4d8b38d)
#define OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_SubjectIdentifier                                 OpenViBE::CIdentifier(0x97c5d20d, 0x203e65b3)
#define OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_TechnicianName                                    OpenViBE::CIdentifier(0xb8a94b68, 0x389393d9)
#define OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_ExperimentDate                                    OpenViBE::CIdentifier(0xbc0266a2, 0x9c2935f1)
#define OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_SubjectAge                                        OpenViBE::CIdentifier(0xc36c6b08, 0x5227380a)
#define OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_TechnicianIdentifier                              OpenViBE::CIdentifier(0xc8ecfbbc, 0x0dcda310)
#define OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_LaboratoryIdentifier                              OpenViBE::CIdentifier(0xe761d3d4, 0x44ba1ebf)
#define OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedHeader                                      OpenViBE::CIdentifier(0x815234bf, 0xaabae5f2)
#define OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedBuffer                                      OpenViBE::CIdentifier(0xaa2738bf, 0xf7fe9fc3)
#define OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedEnd                                         OpenViBE::CIdentifier(0xc4aa114c, 0x628c2d77)

// -----------------------------------------------------
// Channel localisation stream encoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_ChannelLocalisationStreamEncoder                                                               OpenViBE::CIdentifier(0xc4aa738a, 0x2368c0ea)
#define OVP_GD_ClassId_Algorithm_ChannelLocalisationStreamEncoderDesc                                                           OpenViBE::CIdentifier(0x3f7b49a3, 0x2b8f861a)
#define OVP_GD_Algorithm_ChannelLocalisationStreamEncoder_InputParameterId_Matrix                                               OpenViBE::CIdentifier(0xa3e9e5b0, 0xae756303) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputParameterId_Matrix
#define OVP_GD_Algorithm_ChannelLocalisationStreamEncoder_InputParameterId_Dynamic                                              OpenViBE::CIdentifier(0xcf5dd4f8, 0xc2ff2878)
#define OVP_GD_Algorithm_ChannelLocalisationStreamEncoder_OutputParameterId_EncodedMemoryBuffer                                 OpenViBE::CIdentifier(0xa3d8b171, 0xf8734734) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_OutputParameterId_EncodedMemoryBuffer
#define OVP_GD_Algorithm_ChannelLocalisationStreamEncoder_InputTriggerId_EncodeBuffer                                           OpenViBE::CIdentifier(0x1b7076fd, 0x449bc70a) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeBuffer
#define OVP_GD_Algorithm_ChannelLocalisationStreamEncoder_InputTriggerId_EncodeEnd                                              OpenViBE::CIdentifier(0x3fc23508, 0x806753d8) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeEnd
#define OVP_GD_Algorithm_ChannelLocalisationStreamEncoder_InputTriggerId_EncodeHeader                                           OpenViBE::CIdentifier(0x878eaf60, 0xf9d5303f) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeHeader

// -----------------------------------------------------
// Signal stream decoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_SignalStreamDecoder                                                                            OpenViBE::CIdentifier(0x7237c149, 0x0ca66da7)
#define OVP_GD_ClassId_Algorithm_SignalStreamDecoderDesc                                                                        OpenViBE::CIdentifier(0xf1547d89, 0x49ffd0c2)
#define OVP_GD_Algorithm_SignalStreamDecoder_InputParameterId_MemoryBufferToDecode                                              OpenViBE::CIdentifier(0x2f98ea3c, 0xfb0be096) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_InputParameterId_MemoryBufferToDecode
#define OVP_GD_Algorithm_SignalStreamDecoder_OutputParameterId_SamplingRate                                                     OpenViBE::CIdentifier(0x363d8d79, 0xeefb912c)
#define OVP_GD_Algorithm_SignalStreamDecoder_OutputParameterId_Matrix                                                           OpenViBE::CIdentifier(0x79ef3123, 0x35e3ea4d)
#define OVP_GD_Algorithm_SignalStreamDecoder_OutputTriggerId_ReceivedHeader                                                     OpenViBE::CIdentifier(0x815234bf, 0xaabae5f2) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedHeader
#define OVP_GD_Algorithm_SignalStreamDecoder_OutputTriggerId_ReceivedBuffer                                                     OpenViBE::CIdentifier(0xaa2738bf, 0xf7fe9fc3) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedBuffer
#define OVP_GD_Algorithm_SignalStreamDecoder_OutputTriggerId_ReceivedEnd                                                        OpenViBE::CIdentifier(0xc4aa114c, 0x628c2d77) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedEnd

// -----------------------------------------------------
// Spectrum stream encoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_SpectrumStreamEncoder                                                                          OpenViBE::CIdentifier(0xb3e252db, 0xc3214498)
#define OVP_GD_ClassId_Algorithm_SpectrumStreamEncoderDesc                                                                      OpenViBE::CIdentifier(0xd6182973, 0x122ce114)
#define OVP_GD_Algorithm_SpectrumStreamEncoder_InputParameterId_Matrix                                                          OpenViBE::CIdentifier(0xa3e9e5b0, 0xae756303) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputParameterId_Matrix
#define OVP_GD_Algorithm_SpectrumStreamEncoder_InputParameterId_MinMaxFrequencyBands                                            OpenViBE::CIdentifier(0xf5251300, 0x72520e28)
#define OVP_GD_Algorithm_SpectrumStreamEncoder_OutputParameterId_EncodedMemoryBuffer                                            OpenViBE::CIdentifier(0xa3d8b171, 0xf8734734) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_OutputParameterId_EncodedMemoryBuffer
#define OVP_GD_Algorithm_SpectrumStreamEncoder_InputTriggerId_EncodeBuffer                                                      OpenViBE::CIdentifier(0x1b7076fd, 0x449bc70a) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeBuffer
#define OVP_GD_Algorithm_SpectrumStreamEncoder_InputTriggerId_EncodeEnd                                                         OpenViBE::CIdentifier(0x3fc23508, 0x806753d8) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeEnd
#define OVP_GD_Algorithm_SpectrumStreamEncoder_InputTriggerId_EncodeHeader                                                      OpenViBE::CIdentifier(0x878eaf60, 0xf9d5303f) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeHeader

// -----------------------------------------------------
// Acquisition stream decoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_AcquisitionStreamDecoder                                                                       OpenViBE::CIdentifier(0x1e0812b7, 0x3f686dd4)
#define OVP_GD_ClassId_Algorithm_AcquisitionStreamDecoderDesc                                                                   OpenViBE::CIdentifier(0xa01599b0, 0x7f51631a)
#define OVP_GD_Algorithm_AcquisitionStreamDecoder_InputParameterId_MemoryBufferToDecode                                         OpenViBE::CIdentifier(0x2f98ea3c, 0xfb0be096) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_InputParameterId_MemoryBufferToDecode
#define OVP_GD_Algorithm_AcquisitionStreamDecoder_OutputParameterId_StimulationStream                                           OpenViBE::CIdentifier(0x08fc3c12, 0x86a07bf7)
#define OVP_GD_Algorithm_AcquisitionStreamDecoder_OutputParameterId_ChannelUnitsStream                                          OpenViBE::CIdentifier(0x11b93981, 0x6e5da9b0)
#define OVP_GD_Algorithm_AcquisitionStreamDecoder_OutputParameterId_SignalStream                                                OpenViBE::CIdentifier(0x42c0d7bd, 0xbbcea3f3)
#define OVP_GD_Algorithm_AcquisitionStreamDecoder_OutputParameterId_ChannelLocalisationStream                                   OpenViBE::CIdentifier(0x4eb92f81, 0x6ecda6b9)
#define OVP_GD_Algorithm_AcquisitionStreamDecoder_OutputParameterId_BufferDuration                                              OpenViBE::CIdentifier(0x7527d6e5, 0xb7a70339)
#define OVP_GD_Algorithm_AcquisitionStreamDecoder_OutputParameterId_ExperimentInformationStream                                 OpenViBE::CIdentifier(0xa7f1d539, 0xec708539)
#define OVP_GD_Algorithm_AcquisitionStreamDecoder_OutputTriggerId_ReceivedHeader                                                OpenViBE::CIdentifier(0x815234bf, 0xaabae5f2) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedHeader
#define OVP_GD_Algorithm_AcquisitionStreamDecoder_OutputTriggerId_ReceivedBuffer                                                OpenViBE::CIdentifier(0xaa2738bf, 0xf7fe9fc3) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedBuffer
#define OVP_GD_Algorithm_AcquisitionStreamDecoder_OutputTriggerId_ReceivedEnd                                                   OpenViBE::CIdentifier(0xc4aa114c, 0x628c2d77) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedEnd

// -----------------------------------------------------
// Spectrum stream decoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_SpectrumStreamDecoder                                                                          OpenViBE::CIdentifier(0x128202db, 0x449fc7a6)
#define OVP_GD_ClassId_Algorithm_SpectrumStreamDecoderDesc                                                                      OpenViBE::CIdentifier(0x54d18ee8, 0x5dbd913a)
#define OVP_GD_Algorithm_SpectrumStreamDecoder_InputParameterId_MemoryBufferToDecode                                            OpenViBE::CIdentifier(0x2f98ea3c, 0xfb0be096) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_InputParameterId_MemoryBufferToDecode
#define OVP_GD_Algorithm_SpectrumStreamDecoder_OutputParameterId_MinMaxFrequencyBands                                           OpenViBE::CIdentifier(0x375e55e9, 0x9b3666f6)
#define OVP_GD_Algorithm_SpectrumStreamDecoder_OutputParameterId_Matrix                                                         OpenViBE::CIdentifier(0x79ef3123, 0x35e3ea4d) // Duplicate of OVP_GD_Algorithm_SignalStreamDecoder_OutputParameterId_Matrix
#define OVP_GD_Algorithm_SpectrumStreamDecoder_OutputTriggerId_ReceivedHeader                                                   OpenViBE::CIdentifier(0x815234bf, 0xaabae5f2) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedHeader
#define OVP_GD_Algorithm_SpectrumStreamDecoder_OutputTriggerId_ReceivedBuffer                                                   OpenViBE::CIdentifier(0xaa2738bf, 0xf7fe9fc3) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedBuffer
#define OVP_GD_Algorithm_SpectrumStreamDecoder_OutputTriggerId_ReceivedEnd                                                      OpenViBE::CIdentifier(0xc4aa114c, 0x628c2d77) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedEnd

// -----------------------------------------------------
// Stimulation stream decoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_StimulationStreamDecoder                                                                       OpenViBE::CIdentifier(0xc8807f2b, 0x0813c5b1)
#define OVP_GD_ClassId_Algorithm_StimulationStreamDecoderDesc                                                                   OpenViBE::CIdentifier(0x391a615b, 0x71cd888a)
#define OVP_GD_Algorithm_StimulationStreamDecoder_InputParameterId_MemoryBufferToDecode                                         OpenViBE::CIdentifier(0x2f98ea3c, 0xfb0be096) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_InputParameterId_MemoryBufferToDecode
#define OVP_GD_Algorithm_StimulationStreamDecoder_OutputParameterId_StimulationSet                                              OpenViBE::CIdentifier(0xf46d0c19, 0x47306bea)
#define OVP_GD_Algorithm_StimulationStreamDecoder_OutputTriggerId_ReceivedHeader                                                OpenViBE::CIdentifier(0x815234bf, 0xaabae5f2) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedHeader
#define OVP_GD_Algorithm_StimulationStreamDecoder_OutputTriggerId_ReceivedBuffer                                                OpenViBE::CIdentifier(0xaa2738bf, 0xf7fe9fc3) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedBuffer
#define OVP_GD_Algorithm_StimulationStreamDecoder_OutputTriggerId_ReceivedEnd                                                   OpenViBE::CIdentifier(0xc4aa114c, 0x628c2d77) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedEnd

// -----------------------------------------------------
// Streamed matrix stream decoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_StreamedMatrixStreamDecoder                                                                    OpenViBE::CIdentifier(0x7359d0db, 0x91784b21)
#define OVP_GD_ClassId_Algorithm_StreamedMatrixStreamDecoderDesc                                                                OpenViBE::CIdentifier(0x384529d5, 0xd8e0a728)
#define OVP_GD_Algorithm_StreamedMatrixStreamDecoder_InputParameterId_MemoryBufferToDecode                                      OpenViBE::CIdentifier(0x2f98ea3c, 0xfb0be096) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_InputParameterId_MemoryBufferToDecode
#define OVP_GD_Algorithm_StreamedMatrixStreamDecoder_OutputParameterId_Matrix                                                   OpenViBE::CIdentifier(0x79ef3123, 0x35e3ea4d) // Duplicate of OVP_GD_Algorithm_SignalStreamDecoder_OutputParameterId_Matrix
#define OVP_GD_Algorithm_StreamedMatrixStreamDecoder_OutputTriggerId_ReceivedHeader                                             OpenViBE::CIdentifier(0x815234bf, 0xaabae5f2) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedHeader
#define OVP_GD_Algorithm_StreamedMatrixStreamDecoder_OutputTriggerId_ReceivedBuffer                                             OpenViBE::CIdentifier(0xaa2738bf, 0xf7fe9fc3) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedBuffer
#define OVP_GD_Algorithm_StreamedMatrixStreamDecoder_OutputTriggerId_ReceivedEnd                                                OpenViBE::CIdentifier(0xc4aa114c, 0x628c2d77) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedEnd

// -----------------------------------------------------
// Feature vector stream decoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_FeatureVectorStreamDecoder                                                                     OpenViBE::CIdentifier(0xc2689ecc, 0x43b335c1)
#define OVP_GD_ClassId_Algorithm_FeatureVectorStreamDecoderDesc                                                                 OpenViBE::CIdentifier(0xab0ae561, 0xf181e34f)
#define OVP_GD_Algorithm_FeatureVectorStreamDecoder_InputParameterId_MemoryBufferToDecode                                       OpenViBE::CIdentifier(0x2f98ea3c, 0xfb0be096) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_InputParameterId_MemoryBufferToDecode
#define OVP_GD_Algorithm_FeatureVectorStreamDecoder_OutputParameterId_Matrix                                                    OpenViBE::CIdentifier(0x79ef3123, 0x35e3ea4d) // Duplicate of OVP_GD_Algorithm_SignalStreamDecoder_OutputParameterId_Matrix
#define OVP_GD_Algorithm_FeatureVectorStreamDecoder_OutputTriggerId_ReceivedHeader                                              OpenViBE::CIdentifier(0x815234bf, 0xaabae5f2) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedHeader
#define OVP_GD_Algorithm_FeatureVectorStreamDecoder_OutputTriggerId_ReceivedBuffer                                              OpenViBE::CIdentifier(0xaa2738bf, 0xf7fe9fc3) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedBuffer
#define OVP_GD_Algorithm_FeatureVectorStreamDecoder_OutputTriggerId_ReceivedEnd                                                 OpenViBE::CIdentifier(0xc4aa114c, 0x628c2d77) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedEnd

// -----------------------------------------------------
// Channel localisation stream decoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_ChannelLocalisationStreamDecoder                                                               OpenViBE::CIdentifier(0x8222f065, 0xb05d35cf)
#define OVP_GD_ClassId_Algorithm_ChannelLocalisationStreamDecoderDesc                                                           OpenViBE::CIdentifier(0x713a29fd, 0xa5a95e2c)
#define OVP_GD_Algorithm_ChannelLocalisationStreamDecoder_InputParameterId_MemoryBufferToDecode                                 OpenViBE::CIdentifier(0x2f98ea3c, 0xfb0be096) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_InputParameterId_MemoryBufferToDecode
#define OVP_GD_Algorithm_ChannelLocalisationStreamDecoder_OutputParameterId_Matrix                                              OpenViBE::CIdentifier(0x79ef3123, 0x35e3ea4d) // Duplicate of OVP_GD_Algorithm_SignalStreamDecoder_OutputParameterId_Matrix
#define OVP_GD_Algorithm_ChannelLocalisationStreamDecoder_OutputParameterId_Dynamic                                             OpenViBE::CIdentifier(0xd20991fd, 0xa3153651)
#define OVP_GD_Algorithm_ChannelLocalisationStreamDecoder_OutputTriggerId_ReceivedHeader                                        OpenViBE::CIdentifier(0x815234bf, 0xaabae5f2) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedHeader
#define OVP_GD_Algorithm_ChannelLocalisationStreamDecoder_OutputTriggerId_ReceivedBuffer                                        OpenViBE::CIdentifier(0xaa2738bf, 0xf7fe9fc3) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedBuffer
#define OVP_GD_Algorithm_ChannelLocalisationStreamDecoder_OutputTriggerId_ReceivedEnd                                           OpenViBE::CIdentifier(0xc4aa114c, 0x628c2d77) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedEnd

// -----------------------------------------------------
// Channel units stream decoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_ChannelUnitsStreamDecoder                                                                      OpenViBE::CIdentifier(0x5f973ddf, 0x4a582daf)
#define OVP_GD_ClassId_Algorithm_ChannelUnitsStreamDecoderDesc                                                                  OpenViBE::CIdentifier(0x2d59257d, 0x3b1915da)
#define OVP_GD_Algorithm_ChannelUnitsStreamDecoder_InputParameterId_MemoryBufferToDecode                                        OpenViBE::CIdentifier(0x2f98ea3c, 0xfb0be096) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_InputParameterId_MemoryBufferToDecode
#define OVP_GD_Algorithm_ChannelUnitsStreamDecoder_OutputParameterId_Dynamic                                                    OpenViBE::CIdentifier(0x31cf1c7a, 0x17475323)
#define OVP_GD_Algorithm_ChannelUnitsStreamDecoder_OutputParameterId_Matrix                                                     OpenViBE::CIdentifier(0x79ef3123, 0x35e3ea4d) // Duplicate of OVP_GD_Algorithm_SignalStreamDecoder_OutputParameterId_Matrix
#define OVP_GD_Algorithm_ChannelUnitsStreamDecoder_OutputTriggerId_ReceivedHeader                                               OpenViBE::CIdentifier(0x815234bf, 0xaabae5f2) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedHeader
#define OVP_GD_Algorithm_ChannelUnitsStreamDecoder_OutputTriggerId_ReceivedBuffer                                               OpenViBE::CIdentifier(0xaa2738bf, 0xf7fe9fc3) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedBuffer
#define OVP_GD_Algorithm_ChannelUnitsStreamDecoder_OutputTriggerId_ReceivedEnd                                                  OpenViBE::CIdentifier(0xc4aa114c, 0x628c2d77) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputTriggerId_ReceivedEnd

// -----------------------------------------------------
// Experiment information stream encoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_ExperimentInformationStreamEncoder                                                             OpenViBE::CIdentifier(0x56b354fe, 0xbf175468)
#define OVP_GD_ClassId_Algorithm_ExperimentInformationStreamEncoderDesc                                                         OpenViBE::CIdentifier(0x8cc2c754, 0x61665fda)
#define OVP_GD_Algorithm_ExperimentInformationStreamEncoder_InputParameterId_SubjectName                                        OpenViBE::CIdentifier(0x3d3826ea, 0xe8883815) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_SubjectName
#define OVP_GD_Algorithm_ExperimentInformationStreamEncoder_InputParameterId_ExperimentIdentifier                               OpenViBE::CIdentifier(0x40259641, 0x478c73de) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_ExperimentIdentifier
#define OVP_GD_Algorithm_ExperimentInformationStreamEncoder_InputParameterId_LaboratoryName                                     OpenViBE::CIdentifier(0x5ca80fa5, 0x774f01cb) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_LaboratoryName
#define OVP_GD_Algorithm_ExperimentInformationStreamEncoder_InputParameterId_SubjectGender                                      OpenViBE::CIdentifier(0x7d5059e8, 0xe4d8b38d) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_SubjectGender
#define OVP_GD_Algorithm_ExperimentInformationStreamEncoder_InputParameterId_SubjectIdentifier                                  OpenViBE::CIdentifier(0x97c5d20d, 0x203e65b3) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_SubjectIdentifier
#define OVP_GD_Algorithm_ExperimentInformationStreamEncoder_InputParameterId_TechnicianName                                     OpenViBE::CIdentifier(0xb8a94b68, 0x389393d9) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_TechnicianName
#define OVP_GD_Algorithm_ExperimentInformationStreamEncoder_InputParameterId_ExperimentDate                                     OpenViBE::CIdentifier(0xbc0266a2, 0x9c2935f1) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_ExperimentDate
#define OVP_GD_Algorithm_ExperimentInformationStreamEncoder_InputParameterId_SubjectAge                                         OpenViBE::CIdentifier(0xc36c6b08, 0x5227380a) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_SubjectAge
#define OVP_GD_Algorithm_ExperimentInformationStreamEncoder_InputParameterId_TechnicianIdentifier                               OpenViBE::CIdentifier(0xc8ecfbbc, 0x0dcda310) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_TechnicianIdentifier
#define OVP_GD_Algorithm_ExperimentInformationStreamEncoder_InputParameterId_LaboratoryIdentifier                               OpenViBE::CIdentifier(0xe761d3d4, 0x44ba1ebf) // Duplicate of OVP_GD_Algorithm_ExperimentInformationStreamDecoder_OutputParameterId_LaboratoryIdentifier
#define OVP_GD_Algorithm_ExperimentInformationStreamEncoder_OutputParameterId_EncodedMemoryBuffer                               OpenViBE::CIdentifier(0xa3d8b171, 0xf8734734) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_OutputParameterId_EncodedMemoryBuffer
#define OVP_GD_Algorithm_ExperimentInformationStreamEncoder_InputTriggerId_EncodeBuffer                                         OpenViBE::CIdentifier(0x1b7076fd, 0x449bc70a) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeBuffer
#define OVP_GD_Algorithm_ExperimentInformationStreamEncoder_InputTriggerId_EncodeEnd                                            OpenViBE::CIdentifier(0x3fc23508, 0x806753d8) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeEnd
#define OVP_GD_Algorithm_ExperimentInformationStreamEncoder_InputTriggerId_EncodeHeader                                         OpenViBE::CIdentifier(0x878eaf60, 0xf9d5303f) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeHeader

// -----------------------------------------------------
// Acquisition stream encoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_AcquisitionStreamEncoder                                                                       OpenViBE::CIdentifier(0xf9fd2fb5, 0xdf0b3b2c)
#define OVP_GD_ClassId_Algorithm_AcquisitionStreamEncoderDesc                                                                   OpenViBE::CIdentifier(0xe3e0d9eb, 0x4d4eba00)
#define OVP_GD_Algorithm_AcquisitionStreamEncoder_InputParameterId_ChannelUnitsStream                                           OpenViBE::CIdentifier(0x25dd84b4, 0x528524ca)
#define OVP_GD_Algorithm_AcquisitionStreamEncoder_InputParameterId_ChannelLocalisationStream                                    OpenViBE::CIdentifier(0x2cf786e5, 0x520714a1)
#define OVP_GD_Algorithm_AcquisitionStreamEncoder_InputParameterId_ExperimentInformationStream                                  OpenViBE::CIdentifier(0x38755128, 0xcb0c908a)
#define OVP_GD_Algorithm_AcquisitionStreamEncoder_InputParameterId_SignalStream                                                 OpenViBE::CIdentifier(0x4ed9d929, 0x6df5b2b6)
#define OVP_GD_Algorithm_AcquisitionStreamEncoder_InputParameterId_BufferDuration                                               OpenViBE::CIdentifier(0xafa07097, 0x1145b59b)
#define OVP_GD_Algorithm_AcquisitionStreamEncoder_InputParameterId_StimulationStream                                            OpenViBE::CIdentifier(0xcde202ad, 0xf4864ec9)
#define OVP_GD_Algorithm_AcquisitionStreamEncoder_OutputParameterId_EncodedMemoryBuffer                                         OpenViBE::CIdentifier(0xa3d8b171, 0xf8734734) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_OutputParameterId_EncodedMemoryBuffer
#define OVP_GD_Algorithm_AcquisitionStreamEncoder_InputTriggerId_EncodeBuffer                                                   OpenViBE::CIdentifier(0x1b7076fd, 0x449bc70a) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeBuffer
#define OVP_GD_Algorithm_AcquisitionStreamEncoder_InputTriggerId_EncodeEnd                                                      OpenViBE::CIdentifier(0x3fc23508, 0x806753d8) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeEnd
#define OVP_GD_Algorithm_AcquisitionStreamEncoder_InputTriggerId_EncodeHeader                                                   OpenViBE::CIdentifier(0x878eaf60, 0xf9d5303f) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeHeader

// -----------------------------------------------------
// Feature vector stream encoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_FeatureVectorStreamEncoder                                                                     OpenViBE::CIdentifier(0x7ebe049d, 0xf777a602)
#define OVP_GD_ClassId_Algorithm_FeatureVectorStreamEncoderDesc                                                                 OpenViBE::CIdentifier(0xc249527b, 0x89ee1996)
#define OVP_GD_Algorithm_FeatureVectorStreamEncoder_InputParameterId_Matrix                                                     OpenViBE::CIdentifier(0xa3e9e5b0, 0xae756303) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputParameterId_Matrix
#define OVP_GD_Algorithm_FeatureVectorStreamEncoder_OutputParameterId_EncodedMemoryBuffer                                       OpenViBE::CIdentifier(0xa3d8b171, 0xf8734734) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_OutputParameterId_EncodedMemoryBuffer
#define OVP_GD_Algorithm_FeatureVectorStreamEncoder_InputTriggerId_EncodeBuffer                                                 OpenViBE::CIdentifier(0x1b7076fd, 0x449bc70a) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeBuffer
#define OVP_GD_Algorithm_FeatureVectorStreamEncoder_InputTriggerId_EncodeEnd                                                    OpenViBE::CIdentifier(0x3fc23508, 0x806753d8) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeEnd
#define OVP_GD_Algorithm_FeatureVectorStreamEncoder_InputTriggerId_EncodeHeader                                                 OpenViBE::CIdentifier(0x878eaf60, 0xf9d5303f) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeHeader

// -----------------------------------------------------
// Stimulation stream encoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_StimulationStreamEncoder                                                                       OpenViBE::CIdentifier(0x6e86f7d5, 0xa4668108)
#define OVP_GD_ClassId_Algorithm_StimulationStreamEncoderDesc                                                                   OpenViBE::CIdentifier(0x9b994b50, 0x52c3f06a)
#define OVP_GD_Algorithm_StimulationStreamEncoder_InputParameterId_StimulationSet                                               OpenViBE::CIdentifier(0x8565254c, 0x3a49268e)
#define OVP_GD_Algorithm_StimulationStreamEncoder_OutputParameterId_EncodedMemoryBuffer                                         OpenViBE::CIdentifier(0xa3d8b171, 0xf8734734) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_OutputParameterId_EncodedMemoryBuffer
#define OVP_GD_Algorithm_StimulationStreamEncoder_InputTriggerId_EncodeBuffer                                                   OpenViBE::CIdentifier(0x1b7076fd, 0x449bc70a) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeBuffer
#define OVP_GD_Algorithm_StimulationStreamEncoder_InputTriggerId_EncodeEnd                                                      OpenViBE::CIdentifier(0x3fc23508, 0x806753d8) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeEnd
#define OVP_GD_Algorithm_StimulationStreamEncoder_InputTriggerId_EncodeHeader                                                   OpenViBE::CIdentifier(0x878eaf60, 0xf9d5303f) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeHeader

// -----------------------------------------------------
// Channel units stream encoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_ChannelUnitsStreamEncoder                                                                      OpenViBE::CIdentifier(0x2ca034fd, 0x5c051e86)
#define OVP_GD_ClassId_Algorithm_ChannelUnitsStreamEncoderDesc                                                                  OpenViBE::CIdentifier(0x08696dfc, 0x6d415262)
#define OVP_GD_Algorithm_ChannelUnitsStreamEncoder_InputParameterId_Dynamic                                                     OpenViBE::CIdentifier(0x615f03b9, 0x4f6a320a)
#define OVP_GD_Algorithm_ChannelUnitsStreamEncoder_InputParameterId_Matrix                                                      OpenViBE::CIdentifier(0xa3e9e5b0, 0xae756303) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputParameterId_Matrix
#define OVP_GD_Algorithm_ChannelUnitsStreamEncoder_OutputParameterId_EncodedMemoryBuffer                                        OpenViBE::CIdentifier(0xa3d8b171, 0xf8734734) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_OutputParameterId_EncodedMemoryBuffer
#define OVP_GD_Algorithm_ChannelUnitsStreamEncoder_InputTriggerId_EncodeBuffer                                                  OpenViBE::CIdentifier(0x1b7076fd, 0x449bc70a) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeBuffer
#define OVP_GD_Algorithm_ChannelUnitsStreamEncoder_InputTriggerId_EncodeEnd                                                     OpenViBE::CIdentifier(0x3fc23508, 0x806753d8) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeEnd
#define OVP_GD_Algorithm_ChannelUnitsStreamEncoder_InputTriggerId_EncodeHeader                                                  OpenViBE::CIdentifier(0x878eaf60, 0xf9d5303f) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeHeader

// -----------------------------------------------------
// Signal stream encoder
// -----------------------------------------------------

#define OVP_GD_ClassId_Algorithm_SignalStreamEncoder                                                                            OpenViBE::CIdentifier(0xc488ad3c, 0xeb2e36bf)
#define OVP_GD_ClassId_Algorithm_SignalStreamEncoderDesc                                                                        OpenViBE::CIdentifier(0x90ac1e0f, 0x01518200)
#define OVP_GD_Algorithm_SignalStreamEncoder_InputParameterId_SamplingRate                                                      OpenViBE::CIdentifier(0x998710ff, 0x2c5cca82)
#define OVP_GD_Algorithm_SignalStreamEncoder_InputParameterId_Matrix                                                            OpenViBE::CIdentifier(0xa3e9e5b0, 0xae756303) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputParameterId_Matrix
#define OVP_GD_Algorithm_SignalStreamEncoder_OutputParameterId_EncodedMemoryBuffer                                              OpenViBE::CIdentifier(0xa3d8b171, 0xf8734734) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_OutputParameterId_EncodedMemoryBuffer
#define OVP_GD_Algorithm_SignalStreamEncoder_InputTriggerId_EncodeBuffer                                                        OpenViBE::CIdentifier(0x1b7076fd, 0x449bc70a) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeBuffer
#define OVP_GD_Algorithm_SignalStreamEncoder_InputTriggerId_EncodeEnd                                                           OpenViBE::CIdentifier(0x3fc23508, 0x806753d8) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeEnd
#define OVP_GD_Algorithm_SignalStreamEncoder_InputTriggerId_EncodeHeader                                                        OpenViBE::CIdentifier(0x878eaf60, 0xf9d5303f) // Duplicate of OVP_GD_Algorithm_StreamedMatrixStreamEncoder_InputTriggerId_EncodeHeader

#endif // __OpenViBEPlugins_Global_Defines_H__
