# ---------------------------------
# Finds module EBML
# Adds library to target
# Adds include path
# ---------------------------------
OPTION(DYNAMIC_LINK_OPENVIBE_MODULE_EBML "Dynamically link OpenViBE module EBML" ON)

IF(DYNAMIC_LINK_OPENVIBE_MODULE_EBML)
	SET(OPENVIBE_MODULE_EBML_LINKING "")
	ADD_DEFINITIONS(-DEBML_Shared)
ELSE()
	SET(OPENVIBE_MODULE_EBML_LINKING "-static")
	ADD_DEFINITIONS(-DEBML_Static)
ENDIF()

set(PATH_OPENVIBE_MODULES_EBML "PATH_OPENVIBE_MODULES_EBML-NOTFOUND")
set(SRC_DIR ${OV_BASE_DIR}/modules/ebml/include)

FIND_PATH(PATH_OPENVIBE_MODULES_EBML ebml/defines.h PATHS ${SRC_DIR} NO_DEFAULT_PATH)
IF(PATH_OPENVIBE_MODULES_EBML)
	debug_message( "  Found OpenViBE module EBML...")
	INCLUDE_DIRECTORIES(${PATH_OPENVIBE_MODULES_EBML}/)

	TARGET_LINK_LIBRARIES(${PROJECT_NAME} openvibe-module-ebml${OPENVIBE_MODULE_EBML_LINKING})

	ADD_DEFINITIONS(-DTARGET_HAS_EBML)
ELSE(PATH_OPENVIBE_MODULES_EBML)
	MESSAGE(WARNING "  FAILED to find OpenViBE module EBML...")
ENDIF(PATH_OPENVIBE_MODULES_EBML)
