FUNCTION(OV_SET_PROJECT_VERSION)
	SET(PROJECT_VERSION_MAJOR ${OV_GLOBAL_VERSION_MAJOR})

	SET(PROJECT_VERSION_MAJOR ${OV_GLOBAL_VERSION_MAJOR} PARENT_SCOPE)
	SET(PROJECT_VERSION_MINOR ${OV_GLOBAL_VERSION_MINOR})
	SET(PROJECT_VERSION_PATCH ${OV_GLOBAL_VERSION_PATCH})
	SET(PROJECT_VERSION ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH} PARENT_SCOPE)
ENDFUNCTION(OV_SET_PROJECT_VERSION)

